### ISSUE TITLE
Selecting the 8th tradition tree causes my game to crash immediately.

### ISSUE THREAD

**Issue by MalevolentFiber** [OriginalTrinity/More-Ascension-Perk-Slots#4]
I have 7 tradition tree slots selected and I have Ascension Theory researched, but the instant I select the 8th tradition tree my game crashes. I have reinstalled the mod 3 times and nothing has changed.

**Comment by OriginalTrinity** [comment]
I'll need some more info on that. Just telling me something is not working on your side won't do much.
Please include the following for further assistance:

- Your error log
- Stellaris version
- Any other mods you're using and your load order

**Comment by Leanfrog** [comment]
I'm going to say here that I'm having the same issue, seeing as the OP hasn't actually provided anything I'll drop my things in here
Error log is long but just scroll down to the bottom as that's what happened just before the crash
[error.log](https://github.com/OriginalTrinity/More-Ascension-Perk-Slots/files/7491218/error.log)
Mod list is as follows

SLEX
Additional Vanilla Components, Weapons, and Buildings (3 mods, they're just part of a collection)
Machine Shipset
Gigastructural Engineering & More (3.1)
More Ascension Perk Slots
Reduce Aura Graphics
UI Overhaul Dynamic
Tiny Outliner V2
Epic Explosions
Federations - No Hard Feelings for Declined Votes
Portal 2 Advisors
L-Cluster Access (3.1)
Complex Origins
Expanded Gestalts: Forgotten Queens
Little Tee's Emblems
Precursor Story Pack
[3.1.*] New Enclaves
Machine Conciousness
ZerO's Infinity Stones 3.0
!!Universal Modifier Patch (3.1.*)
Xtra Emblems
Psionic Species Expansion
Nanite Expansion
Shut Up We Don't Care! (3.0)
Trait Diversity
Origins Extended
Taskforce Xeno: Alien Invasion Origin

And game version is Lem v3.1.2 (6df7)

I have a feeling it may be a compatibility issue with Gigastructures as that also adds its own traditions

**Comment by OriginalTrinity** [comment]
> I have a feeling it may be a compatibility issue with Gigastructures as that also adds its own traditions

You're kinda right but it's not Gigastructural Engineering since it uses the default tree templates.
It's actually UI Overhaul Dynamic. 

In Stellaris (and any other PDX game) mods are being loaded from top to bottom. If two mods modify the same thing the one that was loaded first will be overridden.
In this case, it's UI Overhaul Dynamic that overrides **topbar_traditions_view.gui** which defines the layout of the tradition window and the tree templates for the categories.

_No template -> no slots for any traditions -> fatal error -> game crash_

So, how do we fix that?
Fairly simple actually. Just put my mod below UI Overhaul Dynamic in your load order.

**Comment by MalevolentFiber** [comment]
Sorry I did not check back up on this, got a bit busy but thank you for providing the solution.
