### ISSUE TITLE
Will the mod be updated for the Aquatic pack?

### ISSUE THREAD

**Issue by Meltee01** [OriginalTrinity/More-Ascension-Perk-Slots#6]
When you get Path of Ascension, you're unable to choose any of the policies within it. Looking forward to an update if you have the time!

**Comment by Meltee01** [comment]
Edit: To clarify, it is only the first tradition in the tree - Individual Strength - which does not function, and requires the console to continue along the tree. 

I consoled _activate_tradition tr_ascension_1_ to give myself the first tradition manually, and the other traditions work as intended once you accrue enough unity. The first tradition, even when consoled, also doesn't appear to be giving the bonuses it describes while remaining "grey" in the Tradition tree even after consoling it.

**Comment by OriginalTrinity** [comment]
As you can see [here](https://github.com/OriginalTrinity/More-Ascension-Perk-Slots/blob/1ca81326e078baa5ca8ac2450c40af036a2a28a3/common/traditions/mas_traditions.txt#L18), the first tradition is locked behind some research. So it is working as intended that you're not able to progress down the tree after adopting it if you don't have said tech.

Since I'm unable to reproduce your issue, I'll need some more info. Please include the following for further assistance:

- Your error log
- Stellaris Version
- Any other mods you're using and their respective load order

**Comment by Meltee01** [comment]
Oh, I never realized it was locked behind a technology before. Sorry for the bug report then lol. What technology is it locked behind?

**Comment by OriginalTrinity** [comment]
As stated in the "_How it works_" section of the description, it's Ascension Theory.
If there's anything else you need help with let me know but please read the description before posting again ;)
